# Generated by Django 4.1.7 on 2023-03-19 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("std", "0002_rename_lesson_topic"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="std",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_in_class",
                to="std.std",
            ),
        ),
    ]
