# Generated by Django 4.1.7 on 2023-03-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("std", "0003_remove_subject_is_active_and_more"),
        ("account", "0003_alter_student_std"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="teaches_in_class",
            field=models.ManyToManyField(blank=True, null=True, to="std.std"),
        ),
    ]
