# Generated by Django 4.1.7 on 2023-03-20 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_teacher_teaches"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="teaches_in_class",
        ),
    ]
