# Generated by Django 4.1.7 on 2023-03-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("std", "0005_remove_std_teachers"),
        ("account", "0006_remove_teacher_teaches_in_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="teaches",
        ),
        migrations.AddField(
            model_name="teacher",
            name="teaches",
            field=models.ManyToManyField(
                null=True, related_name="teaches", to="std.subject"
            ),
        ),
    ]
