# Generated by Django 4.1.7 on 2023-03-20 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_remove_teacher_teaches_teacher_teaches"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="teaches",
        ),
    ]
