# Generated by Django 4.1.7 on 2023-03-19 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("start_date", models.DateField(auto_now_add=True)),
                ("last_updated_on", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Std",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=50)),
                (
                    "class_head",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_head_teacher",
                        to="account.teacher",
                    ),
                ),
                (
                    "students",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_students",
                        to="account.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=250)),
                ("subject_code", models.PositiveSmallIntegerField(unique=True)),
                ("description", models.TextField()),
                ("total_marks", models.CharField(max_length=3)),
                ("passing_marks", models.CharField(max_length=3)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="std.std",
                    ),
                ),
                (
                    "faculty",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_teacher",
                        to="account.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("YT_VIDEO", "YouTube Video"),
                            ("VIMEO_VIDEO", "Vimeo Video"),
                            ("PDF", "PDF"),
                            ("TEXT", "TEXT"),
                        ],
                        default="YT_VIDEO",
                        max_length=50,
                    ),
                ),
                ("video_id", models.CharField(blank=True, max_length=100, null=True)),
                ("text_content", models.TextField(blank=True, null=True)),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="pdf/%Y/%m/"),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="std.chapters"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chapters",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="std.subject"
            ),
        ),
    ]
