# Generated by Django 4.1.7 on 2023-03-19 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("std", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Lesson",
            new_name="Topic",
        ),
    ]
