# Generated by Django 4.1.7 on 2023-03-20 03:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("std", "0002_rename_lesson_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="passing_marks",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="total_marks",
        ),
    ]
