# Generated by Django 4.1.7 on 2023-03-20 04:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("std", "0004_std_teachers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="std",
            name="teachers",
        ),
    ]
