# Generated by Django 4.1.7 on 2023-03-20 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_remove_teacher_teaches"),
        ("std", "0005_remove_std_teachers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subject_teacher",
                to="account.teacher",
            ),
        ),
    ]
