# Generated by Django 4.1.7 on 2023-03-20 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("std", "0006_alter_subject_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapters",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_chapters",
                to="std.subject",
            ),
        ),
    ]
