# Generated by Django 4.1.7 on 2023-03-20 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("std", "0007_alter_chapters_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapter_topics",
                to="std.chapters",
            ),
        ),
    ]
