# Generated by Django 4.1.7 on 2023-03-20 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("std", "0010_assignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="topic",
        ),
    ]
